%% TTAG Calibration Data Fitting (MATLAB)
% ========================================
% Reads calibration_data.xlsx generated by ttag_calibration.py,
% performs polynomial fitting of ADC → Temperature, and finds the
% lowest polynomial order that achieves < 0.1°C max error.
%
% Input:  calibration_data.xlsx (auto-generated by ttag_calibration.py)
% Output:
%   - ttag_fitting_result.png  (comparison plot: fitted curve vs raw data + error distribution)
%   - ttag_coefficients.txt    (polynomial coefficients for Python porting)
%   - Console output with ready-to-use Python code
%
% Key steps:
%   1. Read Excel data, filter invalid points (ADC=0 or ADC=1023)
%   2. Normalize ADC to [-1, 1] for numerical stability
%   3. Scan polynomial orders 2-12, find first with max error < 0.1°C
%   4. Generate comparison plot and export coefficients

clear; clc; close all;

%% ========== 1. 读取数据 ==========
% Excel 文件路径（和 ttag_calibration.py 输出一致）
data_file = 'C:\Users\王应浩\OneDrive\桌面\calibration_data.xlsx';

fprintf('读取数据: %s\n', data_file);
T = readtable(data_file);

% 列名（与 Python 程序输出一致）:
% 序号, 标签ID, 目标温度, 水浴实际温度, ADC均值, ADC极差, ADC采样数, 稳定耗时, 记录时间, 备注
adc_raw = T.("ADC均值");       % ADC 值
temp_true = T.("水浴实际温度"); % 真实温度 (°C)
tag_id = T.("标签ID")(1);      % 标签 ID

fprintf('标签 ID: %d\n', tag_id);
fprintf('数据点数: %d\n', length(adc_raw));
fprintf('ADC 范围: %d ~ %d\n', min(adc_raw), max(adc_raw));
fprintf('温度范围: %.2f°C ~ %.2f°C\n', min(temp_true), max(temp_true));

%% ========== 2. 剔除异常点 (ADC=0 或明显离群) ==========
valid = adc_raw > 0 & adc_raw < 1024;
adc = adc_raw(valid);
temp = temp_true(valid);
fprintf('有效点数: %d (剔除 %d 个异常)\n', sum(valid), sum(~valid));

%% ========== 3. 多项式拟合 ==========
% 将 ADC 归一化到 [-1, 1] 提高数值稳定性
adc_min = min(adc);
adc_max = max(adc);
adc_norm = 2 * (adc - adc_min) / (adc_max - adc_min) - 1;

% 扫描不同阶数，找满足 < 0.1°C 最大误差的最低阶
fprintf('\n=== 多项式拟合扫描 ===\n');
fprintf('%-6s %-12s %-12s %-12s\n', '阶数', 'MaxErr(°C)', 'RMSE(°C)', '状态');
fprintf('------------------------------------------\n');

best_order = 0;
best_p = [];
best_result = [];

for order = 2:12
    try
        [p, ~, mu] = polyfit(adc_norm, temp, order);
        temp_pred = polyval(p, adc_norm, mu);
        errors = abs(temp - temp_pred);
        max_err = max(errors);
        rmse = sqrt(mean(errors .^ 2));

        status = '✅' ;
        if max_err >= 0.1
            status = '❌ >0.1';
        end

        fprintf('%-6d %-12.4f %-12.4f %s\n', order, max_err, rmse, status);

        if max_err < 0.1 && best_order == 0
            best_order = order;
            best_p = p;
            best_mu = mu;
            best_result = struct('order', order, 'max_err', max_err, ...
                                 'rmse', rmse, 'p', p, 'mu', mu);
        end
    catch
        fprintf('%-6d 拟合失败\n', order);
    end
end

%% ========== 4. 最佳结果 ==========
fprintf('\n=== 最佳拟合 ===\n');
if best_order > 0
    fprintf('推荐阶数: %d\n', best_order);
    fprintf('最大误差: %.4f°C\n', best_result.max_err);
    fprintf('均方根误差: %.4f°C\n', best_result.rmse);
    fprintf('\n多项式系数 (ADC 归一化到 [%d, %d] → [-1, 1]):\n', ...
            round(adc_min), round(adc_max));
    fprintf('p1*x^%d + p2*x^%d + ... + p%d*x + p%d\n', ...
            best_order, best_order-1, best_order, best_order+1);
    for i = 1:length(best_p)
        fprintf('  p%-2d = %.15e\n', i, best_p(i));
    end

    % 打印可以直接复制到 Python/ttag_monitor.py 的代码
    fprintf('\n--- Python 温度转换函数 ---\n');
    fprintf('ADC_MIN = %d\n', round(adc_min));
    fprintf('ADC_MAX = %d\n', round(adc_max));
    fprintf('COEFFS = [\n');
    for i = 1:length(best_p)
        fprintf('    %.15e,\n', best_p(i));
    end
    fprintf(']\n');
    fprintf('\ndef adc_to_temperature(adc):\n');
    fprintf('    if adc == 0xFFFF:  # 低电量\n');
    fprintf('        return None\n');
    fprintf('    x = 2.0 * (adc - ADC_MIN) / (ADC_MAX - ADC_MIN) - 1.0\n');
    fprintf('    return sum(c * x**(len(COEFFS)-1-i) for i, c in enumerate(COEFFS))\n');

else
    fprintf('❌ 未找到满足 < 0.1°C 最大误差的拟合!\n');
    fprintf('建议: 增加采样点数或提高 ADC 稳定性要求\n');
end

%% ========== 5. 绘制拟合对比图 ==========
figure('Position', [100 100 1200 500]);

% --- 子图1: 拟合曲线 vs 原始数据 ---
subplot(1, 2, 1);

% 生成密集的 ADC 用于平滑曲线
adc_dense = linspace(min(adc), max(adc), 500)';
adc_dense_norm = 2 * (adc_dense - adc_min) / (adc_max - adc_min) - 1;

% 所有阶数的拟合曲线（对比）
hold on;
colors = lines(5);
legend_entries = {};

% 绘制原始数据点
scatter(adc, temp, 15, 'k', 'filled', 'DisplayName', '实测数据');
legend_entries{1} = '实测数据';

% 绘制最佳拟合
if best_order > 0
    temp_fit = polyval(best_p, adc_dense_norm, best_mu);
    plot(adc_dense, temp_fit, 'r-', 'LineWidth', 2, ...
         'DisplayName', sprintf('%d阶拟合 (MaxErr=%.4f°C)', best_order, best_result.max_err));
    legend_entries{end+1} = sprintf('%d阶拟合 (MaxErr=%.4f°C)', best_order, best_result.max_err);
end

% 也画 5 阶作为对比
try
    [p5, ~, mu5] = polyfit(adc_norm, temp, 5);
    temp_fit5 = polyval(p5, adc_dense_norm, mu5);
    errors5 = abs(temp - polyval(p5, adc_norm, mu5));
    plot(adc_dense, temp_fit5, 'b--', 'LineWidth', 1, ...
         'DisplayName', sprintf('5阶拟合 (MaxErr=%.4f°C)', max(errors5)));
catch
end

xlabel('ADC 值');
ylabel('温度 (°C)');
title(sprintf('TTAG 标定拟合 — 标签 ID=%d, %d 个数据点', tag_id, length(adc)));
legend('Location', 'best');
grid on;
hold off;

% --- 子图2: 误差分布 ---
subplot(1, 2, 2);
hold on;

if best_order > 0
    errors_best = abs(temp - polyval(best_p, adc_norm, best_mu));
    plot(adc, errors_best, 'r.', 'MarkerSize', 8, ...
         'DisplayName', sprintf('%d阶拟合', best_order));
end

plot(adc, abs(temp - polyval(p5, adc_norm, mu5)), 'b.', 'MarkerSize', 6, ...
     'DisplayName', '5阶拟合');

yline(0.1, 'k--', 'LineWidth', 1.5, 'DisplayName', '0.1°C 容差线');
yline(0.05, 'k:', 'LineWidth', 1, 'DisplayName', '0.05°C 容差线');

xlabel('ADC 值');
ylabel('绝对误差 (°C)');
title(sprintf('拟合误差分布 (最佳阶=%d)', best_order));
legend('Location', 'best');
grid on;
hold off;

%% ========== 6. 保存结果 ==========
saveas(gcf, fullfile(fileparts(data_file), 'ttag_fitting_result.png'));
fprintf('\n图表已保存到: %s\n', ...
        fullfile(fileparts(data_file), 'ttag_fitting_result.png'));

% 导出多项式系数
coeff_file = fullfile(fileparts(data_file), 'ttag_coefficients.txt');
fid = fopen(coeff_file, 'w');
fprintf(fid, 'TTAG 标定拟合系数\n');
fprintf(fid, '标签ID: %d\n', tag_id);
fprintf(fid, '数据点: %d\n', length(adc));
fprintf(fid, '拟合阶数: %d\n', best_order);
fprintf(fid, '最大误差: %.4f°C\n', best_result.max_err);
fprintf(fid, 'ADC 范围: %d ~ %d\n', round(adc_min), round(adc_max));
fprintf(fid, '多项式系数 (归一化 ADC → [-1,1]):\n');
for i = 1:length(best_p)
    fprintf(fid, 'p%d = %.15e\n', i, best_p(i));
end
fclose(fid);
fprintf('系数已保存到: %s\n', coeff_file);
